techies_park/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
    path('users/', include("users.urls", namespace="users")),
    path('accounts/', include('registration.backends.default.urls')),
    path("api/v1/events/",include("api.v1.events.urls")),
    path("api/v1/auth/",include("api.v1.auth.urls"))
    
    
]
if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)


    )

users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('otp/', views.otp, name='otp'),
    path("login/", views.login, name='login'),
]

web/urls.py
from django.urls import path
from web import views


app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.manager import UserManager


class User(AbstractUser):
    username=None
    # name=models.CharField(max_length=20)
    phone_number=models.CharField(max_length=15,unique=True)
    is_verified = models.BooleanField(default=False)
    otp=models.CharField(max_length=6)

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS =[]
    objects=UserManager()

users/forms.py
from django import forms
from users.models import User

class UserForm(forms.ModelForm):

    class Meta:
        model=User
        fields=['first_name','phone_number','password']
        widgets={
            'phone_number':forms.NumberInput(attrs={"class": "form-control","placeholder":"Enter your phone number"}),
            'first_name':forms.TextInput(attrs={"class": "form-control","placeholder":"Enter your name"}),
            'password':forms.PasswordInput(attrs={"class": "form-control","placeholder":"Enter your password"})
        }

    def clean(self):
        cleaned_data=super().clean()
        phone_number=cleaned_data.get("phone_number")
        password=cleaned_data.get("password")

        if len(password)<=4:
                self.add_error("password","password must be at least 4 characters")
        if len(str(phone_number))<10:
                self.add_error("phone_number","Invalid phone number")
        if User.objects.filter(phone_number=phone_number).exists():
                self.add_error("phone_number","Phone number already exists")

                

        


    

users/views.py
import random

from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login
from users.forms import UserForm

from users.models import User


# Login functionality
def login(request):

    if request.method == 'POST':
        phone_number = request.POST.get('phone_number')
        password = request.POST.get('password')
        print(phone_number, password)

        if phone_number and password:
            # authenticate user
            user = authenticate(
                request, phone_number=phone_number, password=password)

            if user is not None:
                # login user
                auth_login(request, user)

                return HttpResponseRedirect("/")

        context = {
            "title": "TechiesPark| Login",
            "error": True,
            "message": "Invalid username or password"
        }
        return render(request, "users/login.html", context)
    else:
        context = {
            "title": "TechiesPark| Login",

        }
        return render(request, "users/login.html", context)


# signup functionality
def create(request):

    if request.method == 'POST':
        form=UserForm(request.POST)
        if form.is_valid():

                phone_number=form.cleaned_data["phone_number"]
                password=form.cleaned_data["password"]
                name=form.cleaned_data["first_name"]
                otp = random.randint(1000, 9999)
                user = User.objects.create_user(phone_number=phone_number, otp=otp, is_active=False, first_name=name, password=password)
                user.save()
                context = {
                    "phone_number": phone_number,
                    "title": "TechiesPark| Registration"
                }
                return render(request, 'users/otp.html', context=context)
                    
        else:
                context = {
                    "title": "TechiesPark| Registration",
                    "form": form,
                }
                return render(request, 'users/registration.html', context)

    else:
        form=UserForm()
        context = {
            "title": "TechiesPark| Registration",
            "form": form,
        }
    return render(request, 'users/registration.html', context)


# otp verification
def otp(request):
    otp = request.POST.get('otp')
    phone_number = request.POST.get('phone_number')

    if User.objects.filter(phone_number=phone_number).exists():
        instance = User.objects.get(phone_number=phone_number)

        if instance:

            print(instance.otp)

            if instance.otp == otp:
                instance.is_active = True
                instance.is_verified = True
                instance.save()
                context={
                    "title":"TechiesPark| Login",
                    "message":"Account created successfully, You are ready to go"
                }
                return render(request,"users/login.html",context)
                
            else:
                context = {
                    "message": "Invalid otp",
                    "error": True,
                    "phone_number": phone_number,
                    "title": "TechiesPark| Verification"

                }
                return render(request, 'users/otp.html', context=context)
    else:
        context = {
            "phone_number": phone_number,
            "message": "Invalid Phone number",
            "title": "TechiesPark| Verification",
            
        }
        return render(request, 'users/otp.html', context=context)

templates/users/login.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section id="login">
    <div class="left">
        <div class="content">
            <h2>Techies Park</h2>
            <p>
                Techies park is a technology and entrepreneurship hub, a project
                from Talrop. To build a strong startup ecosystem and accelerate
                startups, Talrop is establishing Techies Parks in all 140
                Assembly constituencies of Kerala.
            </p>
        </div>
    </div>
    <div class="right">
        <div class="logo">
            <img src="{% static 'assets/images/mainlogo.svg' %}" alt="logo" />
        </div>
        <div class="text-logo">
            <img src="{% static 'assets/images/tplogo.png' %}" alt="logo" />
        </div>
        <h4>A project from <span>Talrop</span></h4>
        <p>
            To aid the development of a strong startup ecosystem in our state,
            Talrop has designed Techies park
        </p>
        <form action="/users/login/" method="post">
            {% csrf_token %}
            <label for="">Phone Number</label><br />
            <input
                type="text"
                value=""
                placeholder="Phone Number"
                name="phone_number"
                required
            />
            <label for="">Password</label><br />
            <div class="password">
                <input
                    type="password"
                    value=""
                    placeholder="Password"
                    name="password"
                    required
                />
                <div class="eye-open">
                    <img
                        src="{% static 'assets/images/Eye.svg' %}"
                        alt="eye-open"
                    />
                </div>
                <div class="eye-hide">
                    <img
                        src="https://talrop-techies-park-assets.sgp1.digitaloceanspaces.com/images/Hide.svg"
                        alt="eye-hide"
                    />
                </div>
            </div>
            {%if error %}
            <p class="error" style="color: red">{{message}}</p>
            {% endif %}
            <div class="checkbox">
                <input type="checkbox" name="" id="" />
                <span>Keep me signed in</span>
            </div>
            {% if message %}
            <small>{{message}}</small>
            {% else %}
            <p class="register">Don't have account  <a href="{% url 'users:create' %}">Register</a></p>
            {% endif %}
            <button type="submit">Log In</button>
        </form>
    </div>
</section>
<script src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/users/otp.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
  <h4>Verify OTP</h4>
  <form action="{% url 'users:otp' %}" method="post"  style="display: flex;flex-direction: column; width: 60%;margin: 0 auto;">
    {% csrf_token %}
    <input type="number" name="phone_number" value="{{phone_number}}" id="" style="display: none;"/>
    <label>Enter OTP</label>
    <input type="number" name="otp" id="" class="form-control">
    <small style="color: red;">{{message}}</small>
    <button type="submit" class="btn btn-primary">Verify</button>
  </form>
</div>
{% endblock %}

templates/users/registration.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
    <h1 style="text-align: center;">Register here</h1>
    <form action="{% url 'users:create' %}" method="post"  style="display: flex;flex-direction: column; width: 60%;margin: 0 auto;">
        {% csrf_token %}
        <label for="{{form.first_name.id_for_label}}">{{form.first_name.label}}</label>
        {{form.first_name}}
        {% for error in form.first_name.errors %}
        <small style="color: red;">{{ error }}</small>
        {% endfor %}
        <label for="{{form.phone_number.id_for_label}}">{{form.phone_number.label}}</label>
        {{form.phone_number}}
        {% for error in form.phone_number.errors %}
        <small style="color: red;">{{ error }}</small>
         {% endfor %}
        <label for="{{form.password.id_for_label}}">{{form.password.label}}</label>
        {{form.password}}
        {% for error in form.password.errors %}
        <small style="color: red;">{{ error }}</small>
        {% endfor %}
        <input class="btn btn-primary mt-3" type="submit" value="Submit"  />
    </form>
</div>

{% endblock %}